-- Role: st

-- DROP ROLE st;

CREATE ROLE st LOGIN
  PASSWORD 'pass'
  SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

-- Role: opengeo

-- DROP ROLE opengeo;

CREATE ROLE opengeo LOGIN
  ENCRYPTED PASSWORD 'md576688ec2058178d59b4d9b0b89386096'
  SUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION;
