-- Database: fib

-- DROP DATABASE fib;

CREATE DATABASE fib
  WITH OWNER = st
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'ru_RU.UTF-8'
       LC_CTYPE = 'ru_RU.UTF-8'
       CONNECTION LIMIT = -1;

ALTER DEFAULT PRIVILEGES 
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO public;

ALTER DEFAULT PRIVILEGES 
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO postgres;

ALTER DEFAULT PRIVILEGES 
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO st;

